import type { ChartOfAccountItem } from '@/types/conversion'

export const IFRS_COA_TEMPLATE: ChartOfAccountItem[] = [
  {
    id: 'ifrs-1100',
    code: '1100',
    name: '現金及び現金同等物',
    nameEn: 'Cash and Cash Equivalents',
    standard: 'IFRS',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-1110',
    code: '1110',
    name: '現金',
    nameEn: 'Cash',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'cash',
    normalBalance: 'debit',
    parentId: 'ifrs-1100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-1120',
    code: '1120',
    name: '銀行預金',
    nameEn: 'Bank Balances',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'cash',
    normalBalance: 'debit',
    parentId: 'ifrs-1100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-1200',
    code: '1200',
    name: '金融資産（流動）',
    nameEn: 'Financial Assets - Current',
    standard: 'IFRS',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-1210',
    code: '1210',
    name: '売掛金及びその他の債権',
    nameEn: 'Trade and Other Receivables',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'receivables',
    normalBalance: 'debit',
    parentId: 'ifrs-1200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-1211',
    code: '1211',
    name: '売掛金',
    nameEn: 'Trade Receivables',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'receivables',
    normalBalance: 'debit',
    parentId: 'ifrs-1210',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'ifrs-1212',
    code: '1212',
    name: '貸倒引当金',
    nameEn: 'Allowance for Expected Credit Losses',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'receivables',
    normalBalance: 'credit',
    parentId: 'ifrs-1210',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'ifrs-1220',
    code: '1220',
    name: 'その他の金融資産',
    nameEn: 'Other Financial Assets',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'financial',
    normalBalance: 'debit',
    parentId: 'ifrs-1200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-1300',
    code: '1300',
    name: '棚卸資産',
    nameEn: 'Inventories',
    standard: 'IFRS',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-1310',
    code: '1310',
    name: '商品',
    nameEn: 'Merchandise',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'ifrs-1300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-1320',
    code: '1320',
    name: '原材料',
    nameEn: 'Raw Materials',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'ifrs-1300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-1330',
    code: '1330',
    name: '仕掛品',
    nameEn: 'Work in Progress',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'ifrs-1300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-1340',
    code: '1340',
    name: '完成品',
    nameEn: 'Finished Goods',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'ifrs-1300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-1400',
    code: '1400',
    name: '契約資産',
    nameEn: 'Contract Assets',
    standard: 'IFRS',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-1500',
    code: '1500',
    name: 'その他の流動資産',
    nameEn: 'Other Current Assets',
    standard: 'IFRS',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-1510',
    code: '1510',
    name: '前払費用',
    nameEn: 'Prepayments',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'prepaid',
    normalBalance: 'debit',
    parentId: 'ifrs-1500',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-1520',
    code: '1520',
    name: '当期税金資産',
    nameEn: 'Current Tax Assets',
    standard: 'IFRS',
    category: 'current_asset',
    subcategory: 'tax',
    normalBalance: 'debit',
    parentId: 'ifrs-1500',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-2100',
    code: '2100',
    name: '有形固定資産',
    nameEn: 'Property, Plant and Equipment',
    standard: 'IFRS',
    category: 'fixed_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-2110',
    code: '2110',
    name: '土地',
    nameEn: 'Land',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'debit',
    parentId: 'ifrs-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2120',
    code: '2120',
    name: '建物',
    nameEn: 'Buildings',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'debit',
    parentId: 'ifrs-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2121',
    code: '2121',
    name: '建物減価償却累計額',
    nameEn: 'Accumulated Depreciation - Buildings',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'credit',
    parentId: 'ifrs-2120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'ifrs-2130',
    code: '2130',
    name: '機械装置',
    nameEn: 'Plant and Equipment',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'debit',
    parentId: 'ifrs-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2131',
    code: '2131',
    name: '機械装置減価償却累計額',
    nameEn: 'Accumulated Depreciation - Equipment',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'credit',
    parentId: 'ifrs-2130',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'ifrs-2140',
    code: '2140',
    name: '使用権資産',
    nameEn: 'Right-of-Use Assets',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'lease',
    normalBalance: 'debit',
    parentId: 'ifrs-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2141',
    code: '2141',
    name: '使用権資産減価償却累計額',
    nameEn: 'Accumulated Depreciation - ROU Assets',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'lease',
    normalBalance: 'credit',
    parentId: 'ifrs-2140',
    level: 2,
    isConvertible: true,
  },

  {
    id: 'ifrs-2200',
    code: '2200',
    name: '無形資産',
    nameEn: 'Intangible Assets',
    standard: 'IFRS',
    category: 'fixed_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-2210',
    code: '2210',
    name: 'のれん',
    nameEn: 'Goodwill',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'ifrs-2200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2220',
    code: '2220',
    name: 'ソフトウェア',
    nameEn: 'Computer Software',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'ifrs-2200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2221',
    code: '2221',
    name: 'ソフトウェア償却累計額',
    nameEn: 'Accumulated Amortisation - Software',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'credit',
    parentId: 'ifrs-2220',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'ifrs-2230',
    code: '2230',
    name: '開発費',
    nameEn: 'Development Costs',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'ifrs-2200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2240',
    code: '2240',
    name: '特許権及びライセンス',
    nameEn: 'Patents and Licences',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'ifrs-2200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-2300',
    code: '2300',
    name: '投資不動産',
    nameEn: 'Investment Property',
    standard: 'IFRS',
    category: 'fixed_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-2400',
    code: '2400',
    name: '金融資産（固定）',
    nameEn: 'Financial Assets - Non-current',
    standard: 'IFRS',
    category: 'fixed_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-2410',
    code: '2410',
    name: '子会社株式',
    nameEn: 'Investments in Subsidiaries',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'investment',
    normalBalance: 'debit',
    parentId: 'ifrs-2400',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2420',
    code: '2420',
    name: '関連会社株式',
    nameEn: 'Investments in Associates',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'investment',
    normalBalance: 'debit',
    parentId: 'ifrs-2400',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-2430',
    code: '2430',
    name: '持分法適用関連会社株式',
    nameEn: 'Equity-accounted Investments',
    standard: 'IFRS',
    category: 'fixed_asset',
    subcategory: 'investment',
    normalBalance: 'debit',
    parentId: 'ifrs-2400',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-2500',
    code: '2500',
    name: '繰延税金資産',
    nameEn: 'Deferred Tax Assets',
    standard: 'IFRS',
    category: 'deferred_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'ifrs-3100',
    code: '3100',
    name: '買掛金及びその他の未払債務',
    nameEn: 'Trade and Other Payables',
    standard: 'IFRS',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-3110',
    code: '3110',
    name: '買掛金',
    nameEn: 'Trade Payables',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'trade',
    normalBalance: 'credit',
    parentId: 'ifrs-3100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-3120',
    code: '3120',
    name: 'その他の未払債務',
    nameEn: 'Other Payables',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'other',
    normalBalance: 'credit',
    parentId: 'ifrs-3100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-3121',
    code: '3121',
    name: '未払費用',
    nameEn: 'Accrued Expenses',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'accrued',
    normalBalance: 'credit',
    parentId: 'ifrs-3120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'ifrs-3122',
    code: '3122',
    name: '未払給与',
    nameEn: 'Accrued Salaries',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'accrued',
    normalBalance: 'credit',
    parentId: 'ifrs-3120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'ifrs-3123',
    code: '3123',
    name: '未払法人税',
    nameEn: 'Current Tax Liabilities',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'tax',
    normalBalance: 'credit',
    parentId: 'ifrs-3120',
    level: 2,
    isConvertible: true,
  },

  {
    id: 'ifrs-3200',
    code: '3200',
    name: '契約負債',
    nameEn: 'Contract Liabilities',
    standard: 'IFRS',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-3210',
    code: '3210',
    name: '前受金',
    nameEn: 'Deferred Revenue',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'deferred',
    normalBalance: 'credit',
    parentId: 'ifrs-3200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-3300',
    code: '3300',
    name: '金融負債（流動）',
    nameEn: 'Financial Liabilities - Current',
    standard: 'IFRS',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-3310',
    code: '3310',
    name: '短期借入金',
    nameEn: 'Short-term Borrowings',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'ifrs-3300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-3320',
    code: '3320',
    name: '長期借入金の1年以内返済予定額',
    nameEn: 'Current Portion of Long-term Borrowings',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'ifrs-3300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-3330',
    code: '3330',
    name: 'リース負債（流動）',
    nameEn: 'Lease Liabilities - Current',
    standard: 'IFRS',
    category: 'current_liability',
    subcategory: 'lease',
    normalBalance: 'credit',
    parentId: 'ifrs-3300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-3400',
    code: '3400',
    name: '引当金（流動）',
    nameEn: 'Provisions - Current',
    standard: 'IFRS',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'ifrs-4100',
    code: '4100',
    name: '金融負債（固定）',
    nameEn: 'Financial Liabilities - Non-current',
    standard: 'IFRS',
    category: 'fixed_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-4110',
    code: '4110',
    name: '長期借入金',
    nameEn: 'Long-term Borrowings',
    standard: 'IFRS',
    category: 'fixed_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'ifrs-4100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-4120',
    code: '4120',
    name: '社債',
    nameEn: 'Bonds Payable',
    standard: 'IFRS',
    category: 'fixed_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'ifrs-4100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-4130',
    code: '4130',
    name: 'リース負債（固定）',
    nameEn: 'Lease Liabilities - Non-current',
    standard: 'IFRS',
    category: 'fixed_liability',
    subcategory: 'lease',
    normalBalance: 'credit',
    parentId: 'ifrs-4100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-4200',
    code: '4200',
    name: '退職給付引当金',
    nameEn: 'Employee Benefits',
    standard: 'IFRS',
    category: 'fixed_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-4210',
    code: '4210',
    name: '退職給付債務',
    nameEn: 'Defined Benefit Obligation',
    standard: 'IFRS',
    category: 'fixed_liability',
    subcategory: 'pension',
    normalBalance: 'credit',
    parentId: 'ifrs-4200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-4300',
    code: '4300',
    name: '引当金（固定）',
    nameEn: 'Provisions - Non-current',
    standard: 'IFRS',
    category: 'fixed_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-4310',
    code: '4310',
    name: '製品保証引当金',
    nameEn: 'Warranty Provisions',
    standard: 'IFRS',
    category: 'fixed_liability',
    subcategory: 'provision',
    normalBalance: 'credit',
    parentId: 'ifrs-4300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-4320',
    code: '4320',
    name: '事業再構築引当金',
    nameEn: 'Restructuring Provisions',
    standard: 'IFRS',
    category: 'fixed_liability',
    subcategory: 'provision',
    normalBalance: 'credit',
    parentId: 'ifrs-4300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-4400',
    code: '4400',
    name: '繰延税金負債',
    nameEn: 'Deferred Tax Liabilities',
    standard: 'IFRS',
    category: 'deferred_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'ifrs-5100',
    code: '5100',
    name: '発行済株式資本金',
    nameEn: 'Issued Capital',
    standard: 'IFRS',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-5110',
    code: '5110',
    name: '普通株式',
    nameEn: 'Ordinary Shares',
    standard: 'IFRS',
    category: 'equity',
    subcategory: 'capital',
    normalBalance: 'credit',
    parentId: 'ifrs-5100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-5120',
    code: '5120',
    name: '株式発行溢価',
    nameEn: 'Share Premium',
    standard: 'IFRS',
    category: 'equity',
    subcategory: 'premium',
    normalBalance: 'credit',
    parentId: 'ifrs-5100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-5200',
    code: '5200',
    name: '利益剰余金',
    nameEn: 'Retained Earnings',
    standard: 'IFRS',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-5210',
    code: '5210',
    name: '繰越利益剰余金',
    nameEn: 'Retained Earnings',
    standard: 'IFRS',
    category: 'equity',
    subcategory: 'retained',
    normalBalance: 'credit',
    parentId: 'ifrs-5200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-5220',
    code: '5220',
    name: '自己株式',
    nameEn: 'Treasury Shares',
    standard: 'IFRS',
    category: 'equity',
    subcategory: 'treasury',
    normalBalance: 'debit',
    parentId: 'ifrs-5200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-5300',
    code: '5300',
    name: 'その他の包括利益累計額',
    nameEn: 'Accumulated Other Comprehensive Income',
    standard: 'IFRS',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-5310',
    code: '5310',
    name: '換算調整勘定',
    nameEn: 'Foreign Currency Translation Reserve',
    standard: 'IFRS',
    category: 'equity',
    subcategory: 'oci',
    normalBalance: 'credit',
    parentId: 'ifrs-5300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-5320',
    code: '5320',
    name: '有価証券評価差額金',
    nameEn: 'Fair Value Reserve',
    standard: 'IFRS',
    category: 'equity',
    subcategory: 'oci',
    normalBalance: 'credit',
    parentId: 'ifrs-5300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-5330',
    code: '5330',
    name: 'キャッシュフロー・ヘッジ',
    nameEn: 'Cash Flow Hedge Reserve',
    standard: 'IFRS',
    category: 'equity',
    subcategory: 'oci',
    normalBalance: 'credit',
    parentId: 'ifrs-5300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-5400',
    code: '5400',
    name: '非支配持分',
    nameEn: 'Non-controlling Interests',
    standard: 'IFRS',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'ifrs-6100',
    code: '6100',
    name: '収益',
    nameEn: 'Revenue',
    standard: 'IFRS',
    category: 'revenue',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-6110',
    code: '6110',
    name: '売上高',
    nameEn: 'Revenue from Contracts with Customers',
    standard: 'IFRS',
    category: 'revenue',
    subcategory: 'sales',
    normalBalance: 'credit',
    parentId: 'ifrs-6100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-6120',
    code: '6120',
    name: 'その他の収益',
    nameEn: 'Other Income',
    standard: 'IFRS',
    category: 'revenue',
    subcategory: 'other',
    normalBalance: 'credit',
    parentId: 'ifrs-6100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-7100',
    code: '7100',
    name: '売上原価',
    nameEn: 'Cost of Sales',
    standard: 'IFRS',
    category: 'cogs',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'ifrs-8100',
    code: '8100',
    name: '販売費及び一般管理費',
    nameEn: 'Operating Expenses',
    standard: 'IFRS',
    category: 'sga_expense',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-8110',
    code: '8110',
    name: '従業員給与費用',
    nameEn: 'Employee Benefits Expense',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'personnel',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-8120',
    code: '8120',
    name: '減価償却費及び償却費',
    nameEn: 'Depreciation and Amortisation Expense',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'depreciation',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-8130',
    code: '8130',
    name: '賃借料',
    nameEn: 'Rental Expense',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'rent',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-8140',
    code: '8140',
    name: '修繕費及び維持費',
    nameEn: 'Repairs and Maintenance',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'maintenance',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-8150',
    code: '8150',
    name: '広告宣伝費',
    nameEn: 'Advertising and Promotion',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'marketing',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-8160',
    code: '8160',
    name: '配送費',
    nameEn: 'Distribution Costs',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'logistics',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-8170',
    code: '8170',
    name: '研究開発費',
    nameEn: 'Research and Development Costs',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'rnd',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-8180',
    code: '8180',
    name: 'その他の費用',
    nameEn: 'Other Expenses',
    standard: 'IFRS',
    category: 'sga_expense',
    subcategory: 'other',
    normalBalance: 'debit',
    parentId: 'ifrs-8100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-9100',
    code: '9100',
    name: '財務費用',
    nameEn: 'Finance Costs',
    standard: 'IFRS',
    category: 'non_operating_expense',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-9110',
    code: '9110',
    name: '支払利息',
    nameEn: 'Interest Expense',
    standard: 'IFRS',
    category: 'non_operating_expense',
    subcategory: 'interest',
    normalBalance: 'debit',
    parentId: 'ifrs-9100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-9120',
    code: '9120',
    name: 'リース負債利息',
    nameEn: 'Interest Expense on Lease Liabilities',
    standard: 'IFRS',
    category: 'non_operating_expense',
    subcategory: 'interest',
    normalBalance: 'debit',
    parentId: 'ifrs-9100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-9130',
    code: '9130',
    name: '為替差損',
    nameEn: 'Foreign Exchange Losses',
    standard: 'IFRS',
    category: 'non_operating_expense',
    subcategory: 'fx',
    normalBalance: 'debit',
    parentId: 'ifrs-9100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-9140',
    code: '9140',
    name: '金融資産減損損失',
    nameEn: 'Impairment Loss on Financial Assets',
    standard: 'IFRS',
    category: 'non_operating_expense',
    subcategory: 'impairment',
    normalBalance: 'debit',
    parentId: 'ifrs-9100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-9200',
    code: '9200',
    name: '財務収益',
    nameEn: 'Finance Income',
    standard: 'IFRS',
    category: 'non_operating_income',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-9210',
    code: '9210',
    name: '受取利息',
    nameEn: 'Interest Income',
    standard: 'IFRS',
    category: 'non_operating_income',
    subcategory: 'interest',
    normalBalance: 'credit',
    parentId: 'ifrs-9200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-9220',
    code: '9220',
    name: '配当金',
    nameEn: 'Dividend Income',
    standard: 'IFRS',
    category: 'non_operating_income',
    subcategory: 'dividend',
    normalBalance: 'credit',
    parentId: 'ifrs-9200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-9230',
    code: '9230',
    name: '為替差益',
    nameEn: 'Foreign Exchange Gains',
    standard: 'IFRS',
    category: 'non_operating_income',
    subcategory: 'fx',
    normalBalance: 'credit',
    parentId: 'ifrs-9200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-9300',
    code: '9300',
    name: '法人税',
    nameEn: 'Income Tax Expense',
    standard: 'IFRS',
    category: 'non_operating_expense',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-9310',
    code: '9310',
    name: '当期法人税',
    nameEn: 'Current Tax',
    standard: 'IFRS',
    category: 'non_operating_expense',
    subcategory: 'tax',
    normalBalance: 'debit',
    parentId: 'ifrs-9300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-9320',
    code: '9320',
    name: '繰延税金',
    nameEn: 'Deferred Tax',
    standard: 'IFRS',
    category: 'non_operating_expense',
    subcategory: 'tax',
    normalBalance: 'debit',
    parentId: 'ifrs-9300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-9400',
    code: '9400',
    name: '持分法による投資利益',
    nameEn: 'Share of Profit of Associates',
    standard: 'IFRS',
    category: 'non_operating_income',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-9500',
    code: '9500',
    name: '減損損失',
    nameEn: 'Impairment Loss',
    standard: 'IFRS',
    category: 'extraordinary_loss',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-9510',
    code: '9510',
    name: 'のれん減損損失',
    nameEn: 'Impairment Loss on Goodwill',
    standard: 'IFRS',
    category: 'extraordinary_loss',
    subcategory: 'impairment',
    normalBalance: 'debit',
    parentId: 'ifrs-9500',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'ifrs-9520',
    code: '9520',
    name: '固定資産減損損失',
    nameEn: 'Impairment Loss on PPE',
    standard: 'IFRS',
    category: 'extraordinary_loss',
    subcategory: 'impairment',
    normalBalance: 'debit',
    parentId: 'ifrs-9500',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'ifrs-9600',
    code: '9600',
    name: '固定資産売却益',
    nameEn: 'Gain on Disposal of Assets',
    standard: 'IFRS',
    category: 'non_operating_income',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-9700',
    code: '9700',
    name: '固定資産売却損',
    nameEn: 'Loss on Disposal of Assets',
    standard: 'IFRS',
    category: 'non_operating_expense',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'ifrs-9800',
    code: '9800',
    name: '事業再構築費用',
    nameEn: 'Restructuring Costs',
    standard: 'IFRS',
    category: 'extraordinary_loss',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
]

export const IFRS_COA_METADATA = {
  standard: 'IFRS' as const,
  name: 'IFRS Chart of Accounts',
  nameEn: 'IFRS Chart of Accounts',
  description: '国際財務報告基準に基づく勘定科目表テンプレート（IAS/IFRS準拠）',
  descriptionEn: 'IFRS Chart of Accounts Template (IAS/IFRS compliant)',
  version: 1,
  totalItems: IFRS_COA_TEMPLATE.length,
  categories: {
    assets: IFRS_COA_TEMPLATE.filter((i) => i.category.includes('asset')).length,
    liabilities: IFRS_COA_TEMPLATE.filter((i) => i.category.includes('liability')).length,
    equity: IFRS_COA_TEMPLATE.filter((i) => i.category === 'equity').length,
    revenue: IFRS_COA_TEMPLATE.filter((i) => i.category === 'revenue').length,
    expenses: IFRS_COA_TEMPLATE.filter(
      (i) =>
        i.category === 'cogs' || i.category === 'sga_expense' || i.category.includes('operating')
    ).length,
  },
}
