import type { ChartOfAccountItem } from '@/types/conversion'

export const USGAAP_COA_TEMPLATE: ChartOfAccountItem[] = [
  {
    id: 'us-1100',
    code: '1100',
    name: '現金及び現金同等物',
    nameEn: 'Cash and Cash Equivalents',
    standard: 'USGAAP',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-1110',
    code: '1110',
    name: '現金',
    nameEn: 'Cash',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'cash',
    normalBalance: 'debit',
    parentId: 'us-1100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1120',
    code: '1120',
    name: '普通預金',
    nameEn: 'Demand Deposits',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'cash',
    normalBalance: 'debit',
    parentId: 'us-1100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1130',
    code: '1130',
    name: '定期預金',
    nameEn: 'Time Deposits',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'cash',
    normalBalance: 'debit',
    parentId: 'us-1100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-1200',
    code: '1200',
    name: '有価証券',
    nameEn: 'Marketable Securities',
    standard: 'USGAAP',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-1210',
    code: '1210',
    name: '株式',
    nameEn: 'Equity Securities',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'securities',
    normalBalance: 'debit',
    parentId: 'us-1200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1220',
    code: '1220',
    name: '債券',
    nameEn: 'Debt Securities',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'securities',
    normalBalance: 'debit',
    parentId: 'us-1200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-1300',
    code: '1300',
    name: '売掛金',
    nameEn: 'Accounts Receivable, Net',
    standard: 'USGAAP',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-1310',
    code: '1310',
    name: '売掛金',
    nameEn: 'Accounts Receivable',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'receivables',
    normalBalance: 'debit',
    parentId: 'us-1300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1320',
    code: '1320',
    name: '貸倒引当金',
    nameEn: 'Allowance for Doubtful Accounts',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'receivables',
    normalBalance: 'credit',
    parentId: 'us-1300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-1400',
    code: '1400',
    name: '棚卸資産',
    nameEn: 'Inventories',
    standard: 'USGAAP',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-1410',
    code: '1410',
    name: '商品',
    nameEn: 'Merchandise',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'us-1400',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1420',
    code: '1420',
    name: '原材料',
    nameEn: 'Raw Materials',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'us-1400',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1430',
    code: '1430',
    name: '仕掛品',
    nameEn: 'Work in Process',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'us-1400',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1440',
    code: '1440',
    name: '製品',
    nameEn: 'Finished Goods',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'inventory',
    normalBalance: 'debit',
    parentId: 'us-1400',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-1500',
    code: '1500',
    name: '前払費用',
    nameEn: 'Prepaid Expenses',
    standard: 'USGAAP',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-1510',
    code: '1510',
    name: '前払保険料',
    nameEn: 'Prepaid Insurance',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'prepaid',
    normalBalance: 'debit',
    parentId: 'us-1500',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-1520',
    code: '1520',
    name: '前払賃借料',
    nameEn: 'Prepaid Rent',
    standard: 'USGAAP',
    category: 'current_asset',
    subcategory: 'prepaid',
    normalBalance: 'debit',
    parentId: 'us-1500',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-1600',
    code: '1600',
    name: 'その他流動資産',
    nameEn: 'Other Current Assets',
    standard: 'USGAAP',
    category: 'current_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-2100',
    code: '2100',
    name: '有形固定資産',
    nameEn: 'Property, Plant and Equipment, Net',
    standard: 'USGAAP',
    category: 'fixed_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-2110',
    code: '2110',
    name: '土地',
    nameEn: 'Land',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'debit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2120',
    code: '2120',
    name: '建物',
    nameEn: 'Buildings',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'debit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2130',
    code: '2130',
    name: '建物減価償却累計額',
    nameEn: 'Accumulated Depreciation - Buildings',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'credit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2140',
    code: '2140',
    name: '機械装置',
    nameEn: 'Machinery and Equipment',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'debit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2150',
    code: '2150',
    name: '機械装置減価償却累計額',
    nameEn: 'Accumulated Depreciation - Equipment',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'credit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2160',
    code: '2160',
    name: '車両',
    nameEn: 'Vehicles',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'debit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2170',
    code: '2170',
    name: '車両減価償却累計額',
    nameEn: 'Accumulated Depreciation - Vehicles',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'ppe',
    normalBalance: 'credit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2180',
    code: '2180',
    name: 'リース資産',
    nameEn: 'Lease Assets - Operating Leases',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'lease',
    normalBalance: 'debit',
    parentId: 'us-2100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-2200',
    code: '2200',
    name: '無形固定資産',
    nameEn: 'Intangible Assets, Net',
    standard: 'USGAAP',
    category: 'fixed_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-2210',
    code: '2210',
    name: 'のれん',
    nameEn: 'Goodwill',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'us-2200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2220',
    code: '2220',
    name: 'ソフトウェア',
    nameEn: 'Software',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'us-2200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2230',
    code: '2230',
    name: '特許権',
    nameEn: 'Patents',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'us-2200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2240',
    code: '2240',
    name: '商標権',
    nameEn: 'Trademarks',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'debit',
    parentId: 'us-2200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-2250',
    code: '2250',
    name: '無形資産償却累計額',
    nameEn: 'Accumulated Amortization',
    standard: 'USGAAP',
    category: 'fixed_asset',
    subcategory: 'intangible',
    normalBalance: 'credit',
    parentId: 'us-2200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-2300',
    code: '2300',
    name: '長期投資',
    nameEn: 'Long-term Investments',
    standard: 'USGAAP',
    category: 'fixed_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-2400',
    code: '2400',
    name: '繰延税金資産',
    nameEn: 'Deferred Tax Assets',
    standard: 'USGAAP',
    category: 'deferred_asset',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-3100',
    code: '3100',
    name: '買掛金',
    nameEn: 'Accounts Payable',
    standard: 'USGAAP',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-3200',
    code: '3200',
    name: '未払費用',
    nameEn: 'Accrued Expenses',
    standard: 'USGAAP',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-3210',
    code: '3210',
    name: '未払給与',
    nameEn: 'Accrued Salaries and Wages',
    standard: 'USGAAP',
    category: 'current_liability',
    subcategory: 'accrued',
    normalBalance: 'credit',
    parentId: 'us-3200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-3220',
    code: '3220',
    name: '未払法人税',
    nameEn: 'Accrued Income Taxes',
    standard: 'USGAAP',
    category: 'current_liability',
    subcategory: 'accrued',
    normalBalance: 'credit',
    parentId: 'us-3200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-3230',
    code: '3230',
    name: '未払利息',
    nameEn: 'Accrued Interest',
    standard: 'USGAAP',
    category: 'current_liability',
    subcategory: 'accrued',
    normalBalance: 'credit',
    parentId: 'us-3200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-3240',
    code: '3240',
    name: '未払広告費',
    nameEn: 'Accrued Advertising',
    standard: 'USGAAP',
    category: 'current_liability',
    subcategory: 'accrued',
    normalBalance: 'credit',
    parentId: 'us-3200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-3300',
    code: '3300',
    name: '短期借入金',
    nameEn: 'Short-term Debt',
    standard: 'USGAAP',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-3310',
    code: '3310',
    name: '銀行借入金',
    nameEn: 'Bank Loans',
    standard: 'USGAAP',
    category: 'current_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'us-3300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-3320',
    code: '3320',
    name: '長期借入金の1年以内返済予定額',
    nameEn: 'Current Portion of Long-term Debt',
    standard: 'USGAAP',
    category: 'current_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'us-3300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-3400',
    code: '3400',
    name: '前受金',
    nameEn: 'Deferred Revenue',
    standard: 'USGAAP',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-3500',
    code: '3500',
    name: 'リース債務（流動）',
    nameEn: 'Lease Liabilities - Current',
    standard: 'USGAAP',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-3600',
    code: '3600',
    name: 'その他流動負債',
    nameEn: 'Other Current Liabilities',
    standard: 'USGAAP',
    category: 'current_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-4100',
    code: '4100',
    name: '長期借入金',
    nameEn: 'Long-term Debt',
    standard: 'USGAAP',
    category: 'fixed_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-4110',
    code: '4110',
    name: '銀行長期借入金',
    nameEn: 'Bank Loans - Long-term',
    standard: 'USGAAP',
    category: 'fixed_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'us-4100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-4120',
    code: '4120',
    name: '社債',
    nameEn: 'Bonds Payable',
    standard: 'USGAAP',
    category: 'fixed_liability',
    subcategory: 'debt',
    normalBalance: 'credit',
    parentId: 'us-4100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-4200',
    code: '4200',
    name: 'リース債務（固定）',
    nameEn: 'Lease Liabilities - Non-current',
    standard: 'USGAAP',
    category: 'fixed_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-4300',
    code: '4300',
    name: '退職給付債務',
    nameEn: 'Pension and Other Post-retirement Benefits',
    standard: 'USGAAP',
    category: 'fixed_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-4400',
    code: '4400',
    name: '繰延税金負債',
    nameEn: 'Deferred Tax Liabilities',
    standard: 'USGAAP',
    category: 'deferred_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-4500',
    code: '4500',
    name: 'その他固定負債',
    nameEn: 'Other Non-current Liabilities',
    standard: 'USGAAP',
    category: 'fixed_liability',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-5100',
    code: '5100',
    name: '資本金',
    nameEn: 'Common Stock',
    standard: 'USGAAP',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-5110',
    code: '5110',
    name: '普通株式',
    nameEn: 'Common Stock',
    standard: 'USGAAP',
    category: 'equity',
    subcategory: 'capital',
    normalBalance: 'credit',
    parentId: 'us-5100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-5120',
    code: '5120',
    name: '株式発行溢価',
    nameEn: 'Additional Paid-in Capital',
    standard: 'USGAAP',
    category: 'equity',
    subcategory: 'capital',
    normalBalance: 'credit',
    parentId: 'us-5100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-5200',
    code: '5200',
    name: '利益剰余金',
    nameEn: 'Retained Earnings',
    standard: 'USGAAP',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-5210',
    code: '5210',
    name: '繰越利益剰余金',
    nameEn: 'Retained Earnings',
    standard: 'USGAAP',
    category: 'equity',
    subcategory: 'retained',
    normalBalance: 'credit',
    parentId: 'us-5200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-5220',
    code: '5220',
    name: '自己株式',
    nameEn: 'Treasury Stock',
    standard: 'USGAAP',
    category: 'equity',
    subcategory: 'treasury',
    normalBalance: 'debit',
    parentId: 'us-5200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-5300',
    code: '5300',
    name: 'その他有価証券評価差額金',
    nameEn: 'Accumulated Other Comprehensive Income',
    standard: 'USGAAP',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-5400',
    code: '5400',
    name: '非支配持分',
    nameEn: 'Non-controlling Interest',
    standard: 'USGAAP',
    category: 'equity',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-6100',
    code: '6100',
    name: '売上高',
    nameEn: 'Revenue',
    standard: 'USGAAP',
    category: 'revenue',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-6110',
    code: '6110',
    name: '製品売上高',
    nameEn: 'Product Revenue',
    standard: 'USGAAP',
    category: 'revenue',
    subcategory: 'sales',
    normalBalance: 'credit',
    parentId: 'us-6100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-6120',
    code: '6120',
    name: '役務売上高',
    nameEn: 'Service Revenue',
    standard: 'USGAAP',
    category: 'revenue',
    subcategory: 'sales',
    normalBalance: 'credit',
    parentId: 'us-6100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-6200',
    code: '6200',
    name: '売上値引及び戻り高',
    nameEn: 'Sales Returns and Allowances',
    standard: 'USGAAP',
    category: 'revenue',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-6300',
    code: '6300',
    name: '売上割引',
    nameEn: 'Sales Discounts',
    standard: 'USGAAP',
    category: 'revenue',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-7100',
    code: '7100',
    name: '売上原価',
    nameEn: 'Cost of Sales',
    standard: 'USGAAP',
    category: 'cogs',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-7110',
    code: '7110',
    name: '製品原価',
    nameEn: 'Cost of Products Sold',
    standard: 'USGAAP',
    category: 'cogs',
    subcategory: 'cost',
    normalBalance: 'debit',
    parentId: 'us-7100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-7120',
    code: '7120',
    name: '役務原価',
    nameEn: 'Cost of Services',
    standard: 'USGAAP',
    category: 'cogs',
    subcategory: 'cost',
    normalBalance: 'debit',
    parentId: 'us-7100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-8100',
    code: '8100',
    name: '販売費及び一般管理費',
    nameEn: 'Operating Expenses',
    standard: 'USGAAP',
    category: 'sga_expense',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },

  {
    id: 'us-8110',
    code: '8110',
    name: '販売費',
    nameEn: 'Selling Expenses',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'selling',
    normalBalance: 'debit',
    parentId: 'us-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-8111',
    code: '8111',
    name: '広告宣伝費',
    nameEn: 'Advertising Expense',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'selling',
    normalBalance: 'debit',
    parentId: 'us-8110',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8112',
    code: '8112',
    name: '販売手数料',
    nameEn: 'Sales Commissions',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'selling',
    normalBalance: 'debit',
    parentId: 'us-8110',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8113',
    code: '8113',
    name: '配送費',
    nameEn: 'Delivery Expense',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'selling',
    normalBalance: 'debit',
    parentId: 'us-8110',
    level: 2,
    isConvertible: true,
  },

  {
    id: 'us-8120',
    code: '8120',
    name: '一般管理費',
    nameEn: 'General and Administrative Expenses',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-8121',
    code: '8121',
    name: '給与手当',
    nameEn: 'Salaries and Wages',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8122',
    code: '8122',
    name: '福利厚生費',
    nameEn: 'Employee Benefits',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8123',
    code: '8123',
    name: '賃借料',
    nameEn: 'Rent Expense',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8124',
    code: '8124',
    name: '減価償却費',
    nameEn: 'Depreciation and Amortization',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8125',
    code: '8125',
    name: '旅費交通費',
    nameEn: 'Travel and Entertainment',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8126',
    code: '8126',
    name: '通信費',
    nameEn: 'Communication Expense',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8127',
    code: '8127',
    name: '保険料',
    nameEn: 'Insurance Expense',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8128',
    code: '8128',
    name: '支払手数料',
    nameEn: 'Professional Fees',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },
  {
    id: 'us-8129',
    code: '8129',
    name: '研究開発費',
    nameEn: 'Research and Development',
    standard: 'USGAAP',
    category: 'sga_expense',
    subcategory: 'admin',
    normalBalance: 'debit',
    parentId: 'us-8120',
    level: 2,
    isConvertible: true,
  },

  {
    id: 'us-9100',
    code: '9100',
    name: '営業外収益',
    nameEn: 'Other Income',
    standard: 'USGAAP',
    category: 'non_operating_income',
    normalBalance: 'credit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-9110',
    code: '9110',
    name: '受取利息',
    nameEn: 'Interest Income',
    standard: 'USGAAP',
    category: 'non_operating_income',
    subcategory: 'interest',
    normalBalance: 'credit',
    parentId: 'us-9100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9120',
    code: '9120',
    name: '受取配当金',
    nameEn: 'Dividend Income',
    standard: 'USGAAP',
    category: 'non_operating_income',
    subcategory: 'dividend',
    normalBalance: 'credit',
    parentId: 'us-9100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9130',
    code: '9130',
    name: '為替差益',
    nameEn: 'Foreign Exchange Gain',
    standard: 'USGAAP',
    category: 'non_operating_income',
    subcategory: 'fx',
    normalBalance: 'credit',
    parentId: 'us-9100',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9140',
    code: '9140',
    name: '固定資産売却益',
    nameEn: 'Gain on Sale of Assets',
    standard: 'USGAAP',
    category: 'non_operating_income',
    subcategory: 'gain',
    normalBalance: 'credit',
    parentId: 'us-9100',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-9200',
    code: '9200',
    name: '営業外費用',
    nameEn: 'Other Expense',
    standard: 'USGAAP',
    category: 'non_operating_expense',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-9210',
    code: '9210',
    name: '支払利息',
    nameEn: 'Interest Expense',
    standard: 'USGAAP',
    category: 'non_operating_expense',
    subcategory: 'interest',
    normalBalance: 'debit',
    parentId: 'us-9200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9220',
    code: '9220',
    name: '為替差損',
    nameEn: 'Foreign Exchange Loss',
    standard: 'USGAAP',
    category: 'non_operating_expense',
    subcategory: 'fx',
    normalBalance: 'debit',
    parentId: 'us-9200',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9230',
    code: '9230',
    name: '固定資産売却損',
    nameEn: 'Loss on Sale of Assets',
    standard: 'USGAAP',
    category: 'non_operating_expense',
    subcategory: 'loss',
    normalBalance: 'debit',
    parentId: 'us-9200',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-9300',
    code: '9300',
    name: '法人税等',
    nameEn: 'Income Tax Expense',
    standard: 'USGAAP',
    category: 'non_operating_expense',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-9310',
    code: '9310',
    name: '法人税',
    nameEn: 'Current Income Tax',
    standard: 'USGAAP',
    category: 'non_operating_expense',
    subcategory: 'tax',
    normalBalance: 'debit',
    parentId: 'us-9300',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9320',
    code: '9320',
    name: '繰延税金',
    nameEn: 'Deferred Income Tax',
    standard: 'USGAAP',
    category: 'non_operating_expense',
    subcategory: 'tax',
    normalBalance: 'debit',
    parentId: 'us-9300',
    level: 1,
    isConvertible: true,
  },

  {
    id: 'us-9400',
    code: '9400',
    name: '特別損失',
    nameEn: 'Impairment Loss',
    standard: 'USGAAP',
    category: 'extraordinary_loss',
    normalBalance: 'debit',
    level: 0,
    isConvertible: true,
  },
  {
    id: 'us-9410',
    code: '9410',
    name: '減損損失',
    nameEn: 'Impairment Loss on Long-lived Assets',
    standard: 'USGAAP',
    category: 'extraordinary_loss',
    subcategory: 'impairment',
    normalBalance: 'debit',
    parentId: 'us-9400',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9420',
    code: '9420',
    name: 'のれん減損損失',
    nameEn: 'Goodwill Impairment',
    standard: 'USGAAP',
    category: 'extraordinary_loss',
    subcategory: 'impairment',
    normalBalance: 'debit',
    parentId: 'us-9400',
    level: 1,
    isConvertible: true,
  },
  {
    id: 'us-9430',
    code: '9430',
    name: '事業再編費用',
    nameEn: 'Restructuring Costs',
    standard: 'USGAAP',
    category: 'extraordinary_loss',
    subcategory: 'restructuring',
    normalBalance: 'debit',
    parentId: 'us-9400',
    level: 1,
    isConvertible: true,
  },
]

export const USGAAP_COA_METADATA = {
  standard: 'USGAAP' as const,
  name: 'USGAAP Chart of Accounts',
  nameEn: 'USGAAP Chart of Accounts',
  description: '米国会計基準に基づく勘定科目表テンプレート（ASC準拠）',
  descriptionEn: 'US GAAP Chart of Accounts Template (ASC compliant)',
  version: 1,
  totalItems: USGAAP_COA_TEMPLATE.length,
  categories: {
    assets: USGAAP_COA_TEMPLATE.filter((i) => i.category.includes('asset')).length,
    liabilities: USGAAP_COA_TEMPLATE.filter((i) => i.category.includes('liability')).length,
    equity: USGAAP_COA_TEMPLATE.filter((i) => i.category === 'equity').length,
    revenue: USGAAP_COA_TEMPLATE.filter((i) => i.category === 'revenue').length,
    expenses: USGAAP_COA_TEMPLATE.filter(
      (i) =>
        i.category === 'cogs' || i.category === 'sga_expense' || i.category.includes('operating')
    ).length,
  },
}
