'use client'

import { CashFlowStatementData, MonthlyCashFlow, AccountItem } from '@/services/export'
import { Currency } from '@/services/currency'

interface CashFlowTemplateProps {
  data: CashFlowStatementData
  language: 'ja' | 'en' | 'dual'
  currency: Currency
  exchangeRate?: number
}

export function CashFlowTemplate({
  data,
  language,
  currency: _currency,
  exchangeRate,
}: CashFlowTemplateProps) {
  const lang = language === 'dual' ? 'ja' : language
  const months = data.months

  return (
    <div className="bg-white p-8 print:p-0" id="cash-flow-statement">
      <header className="mb-6 border-b-2 border-gray-800 pb-4 text-center">
        <h1 className="mb-2 text-2xl font-bold">
          {lang === 'en' ? 'Cash Flow Statement' : '資金繰り表'}
        </h1>
        <p className="text-lg text-gray-600">
          {lang === 'en' ? 'Fiscal Year' : '会計年度'}: {data.fiscalYear}
        </p>
        {exchangeRate && (
          <p className="text-sm text-gray-500">USD/JPY: {exchangeRate.toFixed(2)}</p>
        )}
      </header>

      <div className="overflow-x-auto">
        <table className="w-full border-collapse text-xs">
          <thead>
            <tr className="bg-gray-100">
              <th className="min-w-[120px] border p-2 text-left">
                {lang === 'en' ? 'Item' : '項目'}
              </th>
              {months.map((m) => (
                <th key={m.month} className="min-w-[80px] border p-2 text-right">
                  {lang === 'en'
                    ? new Date(data.fiscalYear, m.month - 1).toLocaleDateString('en-US', {
                        month: 'short',
                      })
                    : `${m.month}月`}
                </th>
              ))}
              <th className="min-w-[80px] border bg-blue-50 p-2 text-right">
                {lang === 'en' ? 'Total' : '合計'}
              </th>
            </tr>
          </thead>
          <tbody>
            <OpeningBalanceRow months={months} />

            <CategoryRow
              label={lang === 'en' ? 'Operating Receipts' : '営業収入'}
              months={months}
              getter={(m) => sumItems(m.operatingReceipts)}
              className="bg-green-50"
            />

            {months[0]?.operatingReceipts.map((_, idx) => (
              <DetailRow
                key={`receipt-${idx}`}
                label={months[0]?.operatingReceipts[idx]?.name || ''}
                months={months}
                getter={(m) => m.operatingReceipts[idx]?.amount || 0}
              />
            ))}

            <CategoryRow
              label={lang === 'en' ? 'Operating Payments' : '営業支出'}
              months={months}
              getter={(m) => sumItems(m.operatingPayments)}
              className="bg-red-50"
            />

            {months[0]?.operatingPayments.map((_, idx) => (
              <DetailRow
                key={`payment-${idx}`}
                label={months[0]?.operatingPayments[idx]?.name || ''}
                months={months}
                getter={(m) => m.operatingPayments[idx]?.amount || 0}
              />
            ))}

            <CategoryRow
              label={lang === 'en' ? 'Operating CF' : '営業CF'}
              months={months}
              getter={(m) => m.operatingCashFlow}
              className="bg-blue-100 font-semibold"
              isTotal
            />

            <CategoryRow
              label={lang === 'en' ? 'Investing CF' : '投資CF'}
              months={months}
              getter={(m) => m.investingCashFlow}
            />

            <CategoryRow
              label={lang === 'en' ? 'Financing CF' : '財務CF'}
              months={months}
              getter={(m) => m.financingCashFlow}
            />

            <CategoryRow
              label={lang === 'en' ? 'Net Change' : '収支差引'}
              months={months}
              getter={(m) => m.netChange}
              className="bg-yellow-50 font-semibold"
              isTotal
            />

            <ClosingBalanceRow months={months} />
          </tbody>
        </table>
      </div>

      <footer className="mt-6 border-t pt-4 text-center text-xs text-gray-500">
        <p>
          {lang === 'en'
            ? 'This report was generated by freee_audit system.'
            : 'このレポートはfreee_auditシステムにより生成されました。'}
        </p>
      </footer>
    </div>
  )
}

interface CategoryRowProps {
  label: string
  months: MonthlyCashFlow[]
  getter: (m: MonthlyCashFlow) => number
  className?: string
  isTotal?: boolean
}

function CategoryRow({ label, months, getter, className = '', isTotal = false }: CategoryRowProps) {
  const total = months.reduce((sum, m) => sum + getter(m), 0)

  return (
    <tr className={`border ${className}`}>
      <td className={`border p-2 ${isTotal ? 'font-semibold' : 'font-medium'}`}>{label}</td>
      {months.map((m) => (
        <td key={m.month} className="border p-2 text-right">
          {formatValue(getter(m))}
        </td>
      ))}
      <td className="border bg-blue-50 p-2 text-right font-semibold">{formatValue(total)}</td>
    </tr>
  )
}

interface DetailRowProps {
  label: string
  months: MonthlyCashFlow[]
  getter: (m: MonthlyCashFlow) => number
}

function DetailRow({ label, months, getter }: DetailRowProps) {
  const total = months.reduce((sum, m) => sum + getter(m), 0)

  return (
    <tr className="border">
      <td className="border p-2 pl-6 text-gray-600">{label}</td>
      {months.map((m) => (
        <td key={m.month} className="border p-2 text-right text-gray-600">
          {formatValue(getter(m))}
        </td>
      ))}
      <td className="border p-2 text-right text-gray-600">{formatValue(total)}</td>
    </tr>
  )
}

interface OpeningBalanceRowProps {
  months: MonthlyCashFlow[]
}

function OpeningBalanceRow({ months }: OpeningBalanceRowProps) {
  return (
    <tr className="border bg-gray-50 font-semibold">
      <td className="border p-2">期首残高</td>
      {months.map((m) => (
        <td key={m.month} className="border p-2 text-right">
          {formatValue(m.openingBalance)}
        </td>
      ))}
      <td className="border bg-gray-100 p-2 text-right">-</td>
    </tr>
  )
}

interface ClosingBalanceRowProps {
  months: MonthlyCashFlow[]
}

function ClosingBalanceRow({ months }: ClosingBalanceRowProps) {
  const lastMonth = months[months.length - 1]
  return (
    <tr className="border bg-green-100 font-bold">
      <td className="border p-2">期末残高</td>
      {months.map((m) => (
        <td key={m.month} className="border p-2 text-right">
          {formatValue(m.closingBalance)}
        </td>
      ))}
      <td className="border bg-green-200 p-2 text-right">
        {formatValue(lastMonth?.closingBalance || 0)}
      </td>
    </tr>
  )
}

function sumItems(items: AccountItem[]): number {
  return items.reduce((sum, item) => sum + item.amount, 0)
}

function formatValue(value: number): string {
  const absValue = Math.abs(value)
  const formatted =
    absValue >= 1000000
      ? `${(absValue / 1000000).toFixed(1)}M`
      : absValue >= 1000
        ? `${(absValue / 1000).toFixed(0)}K`
        : absValue.toString()

  const sign = value < 0 ? '-' : ''
  return `${sign}${formatted}`
}

export default CashFlowTemplate
