'use client'

import { KPIData, KPIItem } from '@/services/export'

interface KPIReportTemplateProps {
  data: KPIData
  language: 'ja' | 'en' | 'dual'
  previousData?: KPIData
}

export function KPIReportTemplate({ data, language, previousData }: KPIReportTemplateProps) {
  const lang = language === 'dual' ? 'ja' : language

  const categories: { key: keyof KPIData; title: string; titleEn: string }[] = [
    { key: 'profitability', title: '収益性指標', titleEn: 'Profitability' },
    { key: 'efficiency', title: '効率性指標', titleEn: 'Efficiency' },
    { key: 'safety', title: '安全性指標', titleEn: 'Safety' },
    { key: 'growth', title: '成長性指標', titleEn: 'Growth' },
    { key: 'cashFlow', title: 'キャッシュフロー指標', titleEn: 'Cash Flow' },
  ]

  return (
    <div className="bg-white p-8 print:p-0" id="kpi-report">
      <header className="mb-6 border-b-2 border-gray-800 pb-4 text-center">
        <h1 className="mb-2 text-2xl font-bold">
          {lang === 'en' ? 'Key Performance Indicators' : '経営指標レポート'}
        </h1>
        <p className="text-lg text-gray-600">
          {data.fiscalYear} {lang === 'en' ? 'Fiscal Year' : '年度'} / {data.month}{' '}
          {lang === 'en' ? 'Month' : '月'}
        </p>
      </header>

      {categories.map((category) => {
        const kpis = data[category.key] as KPIItem[]
        if (!kpis || kpis.length === 0) return null

        return (
          <section key={category.key} className="mb-6">
            <h2 className="mb-3 border-b pb-2 text-lg font-bold">
              {lang === 'en' ? category.titleEn : category.title}
            </h2>
            <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
              {kpis.map((kpi: KPIItem) => (
                <KPICard
                  key={kpi.key}
                  kpi={kpi}
                  previousKpi={(previousData?.[category.key] as KPIItem[] | undefined)?.find(
                    (k: KPIItem) => k.key === kpi.key
                  )}
                  language={lang}
                />
              ))}
            </div>
          </section>
        )
      })}

      <footer className="mt-6 border-t pt-4 text-center text-xs text-gray-500">
        <p>
          {lang === 'en'
            ? 'This report was generated by freee_audit system.'
            : 'このレポートはfreee_auditシステムにより生成されました。'}
        </p>
      </footer>
    </div>
  )
}

interface KPICardProps {
  kpi: KPIItem
  previousKpi?: KPIItem
  language: 'ja' | 'en'
}

function KPICard({ kpi, previousKpi, language }: KPICardProps) {
  const trend = getTrend(kpi, previousKpi)
  const trendColor =
    trend === 'up' ? 'text-green-600' : trend === 'down' ? 'text-red-600' : 'text-gray-500'
  const trendIcon = trend === 'up' ? '↑' : trend === 'down' ? '↓' : '→'

  const isGoodTrend = (trend: string, key: string) => {
    if (trend === 'stable') return true
    const inverseIndicators = ['burnRate', 'debtEquityRatio']
    if (inverseIndicators.includes(key)) {
      return trend === 'down'
    }
    return trend === 'up'
  }

  const goodTrend = isGoodTrend(trend, kpi.key)
  const bgColor = trend === 'stable' ? 'bg-gray-50' : goodTrend ? 'bg-green-50' : 'bg-red-50'

  return (
    <div className={`${bgColor} rounded-lg border p-4`}>
      <div className="mb-2 flex items-start justify-between">
        <p className="flex-1 truncate text-xs text-gray-500">
          {language === 'en' ? kpi.nameEn : kpi.name}
        </p>
        {previousKpi && <span className={`text-xs ${trendColor} ml-2`}>{trendIcon}</span>}
      </div>

      <div className="flex items-baseline gap-1">
        <span className="text-2xl font-bold">{formatKPIValue(kpi.value, kpi.unit)}</span>
        <span className="text-sm text-gray-500">{kpi.unit}</span>
      </div>

      {kpi.target !== undefined && (
        <div className="mt-2">
          <div className="mb-1 flex justify-between text-xs text-gray-500">
            <span>
              {language === 'en' ? 'Target' : '目標'}: {formatKPIValue(kpi.target, kpi.unit)}
            </span>
            <span>{Math.min(100, Math.round((kpi.value / kpi.target) * 100))}%</span>
          </div>
          <div className="h-1.5 w-full rounded-full bg-gray-200">
            <div
              className={`h-1.5 rounded-full ${kpi.value >= kpi.target ? 'bg-green-500' : 'bg-blue-500'}`}
              style={{ width: `${Math.min(100, (kpi.value / kpi.target) * 100)}%` }}
            />
          </div>
        </div>
      )}

      {previousKpi && (
        <p className="mt-2 text-xs text-gray-400">
          {language === 'en' ? 'Previous' : '前期'}:{' '}
          {formatKPIValue(previousKpi.value, previousKpi.unit)}
        </p>
      )}
    </div>
  )
}

function getTrend(current: KPIItem, previous?: KPIItem): 'up' | 'down' | 'stable' {
  if (!previous) return 'stable'

  const change = current.value - previous.value
  const threshold = Math.abs(previous.value) * 0.01 // 1% threshold

  if (Math.abs(change) < threshold) return 'stable'
  return change > 0 ? 'up' : 'down'
}

function formatKPIValue(value: number, unit: string): string {
  if (unit === '%') {
    return value.toFixed(1)
  }
  if (unit === '回') {
    return value.toFixed(2)
  }
  if (unit === '円' || unit === '¥') {
    if (value >= 1000000000) {
      return `${(value / 1000000000).toFixed(1)}B`
    }
    if (value >= 1000000) {
      return `${(value / 1000000).toFixed(1)}M`
    }
    if (value >= 1000) {
      return `${(value / 1000).toFixed(0)}K`
    }
    return value.toFixed(0)
  }
  return value.toFixed(1)
}

export default KPIReportTemplate
